vim.cmd[[highlight CursorLine cterm=NONE ctermbg=227]]
vim.cmd[[highlight Visual ctermfg=NONE ctermbg=11]]
vim.cmd[[highlight MatchParen ctermfg=Black ctermbg=LightCyan]]
vim.cmd[[highlight CursorLineNr term=none cterm=none ctermfg=202]]
vim.cmd[[highlight Search term=none cterm=none ctermfg=Black ctermbg=LightCyan]]
